import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { OoxmlPackage } from "../src/ooxml/package.ts";
import { decodeXml } from "../src/ooxml/xml.ts";
import { diffDocuments } from "../src/core/document-diff.ts";
import { semanticSnapshot, readSemantic } from "../src/ooxml/semantic.ts";
import { DocxError } from "../src/errors.ts";
import { fixtureBytes, encryptedMemberFixture } from "./fixture-builder.mjs";

test("bounded intake inventories relationships and cross-run semantic text", () => { const pkg = OoxmlPackage.fromBytes(fixtureBytes({ external: true })), manifest = pkg.manifest(), snapshot = semanticSnapshot(pkg), read = readSemantic(snapshot, { path: "unused", query: "Hello world", exact: true }); assert.equal(manifest.externalRelationships.length, 1); assert.equal(snapshot.inventory.paragraphs, 3); assert.equal(read.totalMatches, 1); assert.equal(read.blocks[0].text, "Hello world"); assert.equal(read.blocks[0].selector.kind, "paragraphId"); });

test("no-op ZIP rebuild preserves every uncompressed part", () => { const before = OoxmlPackage.fromBytes(fixtureBytes()), after = OoxmlPackage.fromBytes(before.archive.toBytes()), comparison = before.compareIntegrity(after, new Set()); assert.equal(comparison.ok, true); assert.deepEqual(comparison.changedParts, []); });

test("macro and signed packages fail closed for mutation", () => { for (const options of [{ macro: true }, { signed: true }]) { const pkg = OoxmlPackage.fromBytes(fixtureBytes(options)); assert.throws(() => pkg.assertMutationAllowed(), (error) => error instanceof DocxError && ["ACTIVE_CONTENT_BLOCKED", "SIGNED_DOCUMENT"].includes(error.code)); } });

test("encrypted members, DTDs, trailing ZIP data, and tight limits are rejected", () => { assert.throws(() => OoxmlPackage.fromBytes(encryptedMemberFixture()), (error) => error.code === "ENCRYPTED_PACKAGE"); assert.throws(() => semanticSnapshot(OoxmlPackage.fromBytes(fixtureBytes({ dtd: true }))), (error) => error.code === "INVALID_PACKAGE"); assert.throws(() => OoxmlPackage.fromBytes(Buffer.concat([fixtureBytes(), Buffer.from([0])])), (error) => error.code === "INVALID_PACKAGE"); assert.throws(() => OoxmlPackage.fromBytes(fixtureBytes(), { maxArchiveBytes: 100 }), (error) => error.code === "LIMIT_EXCEEDED"); });

test("UTF-16 XML, table-row hashes, and semantic search limits are enforced", () => { const utf16 = Buffer.concat([Buffer.from([0xff, 0xfe]), Buffer.from('<?xml version="1.0" encoding="UTF-16"?><root>ok</root>', "utf16le")]); assert.match(decodeXml(utf16, "fixture.xml", 10_000), /<root>ok<\/root>/); const snapshot = semanticSnapshot(OoxmlPackage.fromBytes(fixtureBytes())), row = snapshot.stories[0].tables[0].rows[0]; const selected = readSemantic(snapshot, { path: "unused", selector: { kind: "tableRow", table: 1, row: 1, expectedHash: row.hash } }); assert.equal(selected.blocks[0].hash, row.hash); assert.throws(() => readSemantic(snapshot, { path: "unused", selector: { kind: "tableRow", table: 1, row: 1, expectedHash: "0".repeat(16) } }), (error) => error.code === "SOURCE_CHANGED"); const limited = readSemantic(snapshot, { path: "unused", maxBlocks: 100, limits: { maxSearchMatches: 1 } }); assert.equal(limited.blocks.length, 1); assert.equal(limited.truncated, true); });

test("text boxes are exposed as a dedicated semantic story", () => { const archive = OoxmlPackage.fromBytes(fixtureBytes()).archive, document = Buffer.from(archive.require("word/document.xml")).toString("utf8").replace("<w:sectPr/>", "<w:txbxContent><w:p><w:r><w:t>Text box content</w:t></w:r></w:p></w:txbxContent><w:sectPr/>"); archive.set("word/document.xml", Buffer.from(document)); const snapshot = semanticSnapshot(OoxmlPackage.fromBytes(archive.toBytes())), textbox = snapshot.stories.find((story) => story.kind === "textbox"); assert.equal(snapshot.inventory.textBoxes, 1); assert.equal(textbox.paragraphs[0].text, "Text box content"); assert.equal(snapshot.stories.find((story) => story.kind === "main").paragraphs.some((paragraph) => paragraph.text === "Text box content"), false); assert.equal(readSemantic(snapshot, { path: "unused", stories: ["textbox"], query: "Text box content" }).totalMatches, 1); });

test("semantic/package diff honors bounded formatting and package-detail options", () => { const before = OoxmlPackage.fromBytes(fixtureBytes()), archive = OoxmlPackage.fromBytes(fixtureBytes()).archive, changedXml = Buffer.from(archive.require("word/document.xml")).toString("utf8").replace("Hello ", "Goodbye "); archive.set("word/document.xml", Buffer.from(changedXml)); const after = OoxmlPackage.fromBytes(archive.toBytes()), detailed = diffDocuments(before, after, semanticSnapshot(before), semanticSnapshot(after), { maxChanges: 1 }); assert.equal(detailed.equal, false); assert.equal(detailed.semanticChangeCount, 1); assert.deepEqual(detailed.changedParts, ["word/document.xml"]); const compact = diffDocuments(before, after, semanticSnapshot(before), semanticSnapshot(after), { includeFormatting: false, includePackageParts: false }); assert.equal(compact.changedParts, undefined); assert.equal(compact.changedPartCount, 1); });

test("duplicate content types and macro-enabled main content are fail-closed", () => { const duplicate = OoxmlPackage.fromBytes(fixtureBytes()).archive, contentTypes = Buffer.from(duplicate.require("[Content_Types].xml")).toString("utf8").replace("</Types>", '<Default Extension="xml" ContentType="application/xml"/></Types>'); duplicate.set("[Content_Types].xml", Buffer.from(contentTypes)); assert.throws(() => OoxmlPackage.fromBytes(duplicate.toBytes()), (error) => error.code === "INVALID_PACKAGE"); const macroTyped = OoxmlPackage.fromBytes(fixtureBytes()).archive, macroTypes = Buffer.from(macroTyped.require("[Content_Types].xml")).toString("utf8").replace("application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml", "application/vnd.ms-word.document.macroEnabled.main+xml"); macroTyped.set("[Content_Types].xml", Buffer.from(macroTypes)); assert.throws(() => OoxmlPackage.fromBytes(macroTyped.toBytes()).assertMutationAllowed(), (error) => error.code === "ACTIVE_CONTENT_BLOCKED"); });
