import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { OoxmlPackage } from "../src/ooxml/package.ts";
import { sha256File } from "../src/core/hash.ts";
import { stageEdit, commitRevision } from "../src/core/transaction.ts";
import { writeFixture } from "./fixture-builder.mjs";

function fakeSidecar(options = {}) { return { async probe() { return { available: true, operations: [], constraints: [], formats: ["docx"], engine: "openxml-sidecar" }; }, async request(command, input) { if (command === "edit") { const pkg = OoxmlPackage.fromBytes(await fs.readFile(input.sourcePath)); const xml = Buffer.from(pkg.archive.require("word/document.xml")).toString("utf8").replace("Hello ", "Goodbye "); pkg.archive.set("word/document.xml", Buffer.from(xml)); if (options.rewriteCore) pkg.archive.set("docProps/core.xml", Buffer.from(Buffer.from(pkg.archive.require("docProps/core.xml")).toString("utf8").replace("Fixture", "Unwanted sidecar rewrite"))); await fs.writeFile(input.outputPath, pkg.archive.toBytes()); } return { protocolVersion: "1.0", ok: true, engineVersion: "test", result: command === "validate" ? { valid: true, errorCount: 0, reopen: true } : { resolved: true } }; } }; }

test("edit stages only, commit is queued and save-as is hash protected", async (t) => { const cwd = await fs.mkdtemp(path.join(os.tmpdir(), "pi-docx-transaction-")); t.after(() => fs.rm(cwd, { recursive: true, force: true })); const source = await writeFixture(path.join(cwd, "source.docx")), sourceHash = await sha256File(source), sidecar = fakeSidecar(); const staged = await stageEdit(source, { path: source, dryRun: false, expectedSourceSha256: sourceHash, operations: [{ type: "replaceText", find: "Hello ", replacement: "Goodbye ", expectedCount: 1 }] }, sidecar); assert.equal(await sha256File(source), sourceHash); assert.notEqual(staged.stagedSha256, sourceHash); const output = path.join(cwd, "output.docx"); let queued = false; const committed = await commitRevision({ revisionId: staged.revisionId, destinationPath: output, expectedSourceSha256: sourceHash }, cwd, async (key, work) => { assert.equal(key, output); queued = true; return work(); }, sidecar); assert.equal(queued, true); assert.equal(committed.outputSha256, staged.stagedSha256); assert.equal(await sha256File(source), sourceHash); });

test("surgical transplantation discards undeclared sidecar rewrites", async (t) => { const cwd = await fs.mkdtemp(path.join(os.tmpdir(), "pi-docx-surgical-")); t.after(() => fs.rm(cwd, { recursive: true, force: true })); const source = await writeFixture(path.join(cwd, "source.docx")), sourceHash = await sha256File(source); const staged = await stageEdit(source, { path: source, dryRun: false, expectedSourceSha256: sourceHash, operations: [{ type: "replaceText", find: "Hello ", replacement: "Goodbye ", expectedCount: 1 }] }, fakeSidecar({ rewriteCore: true })); assert.deepEqual(staged.surgicalTransplant.discardedSidecarChanges, ["docProps/core.xml"]); const sourcePackage = OoxmlPackage.fromBytes(await fs.readFile(source)), stagedPackage = OoxmlPackage.fromBytes(await fs.readFile(staged.stagedPath)); assert.deepEqual(Buffer.from(stagedPackage.archive.require("docProps/core.xml")), Buffer.from(sourcePackage.archive.require("docProps/core.xml"))); });

test("in-place commit retains an exact original recovery copy", async (t) => { const cwd = await fs.mkdtemp(path.join(os.tmpdir(), "pi-docx-recovery-")); t.after(() => fs.rm(cwd, { recursive: true, force: true })); const source = await writeFixture(path.join(cwd, "source.docx")), sourceHash = await sha256File(source), sidecar = fakeSidecar(); const staged = await stageEdit(source, { path: source, dryRun: false, expectedSourceSha256: sourceHash, operations: [{ type: "replaceText", find: "Hello ", replacement: "Goodbye ", expectedCount: 1 }] }, sidecar); const committed = await commitRevision({ revisionId: staged.revisionId, inPlace: true, overwrite: true, expectedSourceSha256: sourceHash }, cwd, async (_key, work) => work(), sidecar); assert.ok(committed.recoveryPath); assert.equal(await sha256File(committed.recoveryPath), sourceHash); assert.equal(await sha256File(source), staged.stagedSha256); });

test("source hash drift refuses staged apply", async (t) => { const cwd = await fs.mkdtemp(path.join(os.tmpdir(), "pi-docx-conflict-")); t.after(() => fs.rm(cwd, { recursive: true, force: true })); const source = await writeFixture(path.join(cwd, "source.docx")); await assert.rejects(stageEdit(source, { path: source, dryRun: false, expectedSourceSha256: "0".repeat(64), operations: [{ type: "replaceText", find: "Hello", replacement: "Bye", expectedCount: 1 }] }, fakeSidecar()), (error) => error.code === "SOURCE_CHANGED"); });
