#!/usr/bin/env node
import { createHash, randomUUID } from "node:crypto";
import { spawnSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

const sha256=(value)=>createHash("sha256").update(value).digest("hex");
const readJson=(file)=>JSON.parse(fs.readFileSync(file,"utf8"));
function parseArgs(argv){const out={action:argv[0]||"",manifest:"",stateDir:"",planFile:"",receiptFile:""}; for(let i=1;i<argv.length;i++){if(argv[i]==="--manifest")out.manifest=argv[++i]||""; else if(argv[i]==="--state-dir")out.stateDir=argv[++i]||""; else if(argv[i]==="--plan-file")out.planFile=argv[++i]||""; else if(argv[i]==="--receipt-file")out.receiptFile=argv[++i]||"";} return out;}
function contained(root,file){const resolved=path.resolve(root,file); const relative=path.relative(root,resolved); if(relative.startsWith("..")||path.isAbsolute(relative))throw new Error(`Path escapes root: ${file}`); return resolved;}
function resolveTarget(manifest,env=process.env){
  const manifestRoot=path.dirname(env.PI_PATCH_MANIFEST_PATH||"");
  const source=contained(manifestRoot,manifest.install.source);
  const configuredAgent=env.PI_AGENT_DIR||path.join(os.homedir(),".pi","agent");
  const agentRoot=fs.existsSync(configuredAgent)?fs.realpathSync(configuredAgent):path.resolve(configuredAgent);
  const target=contained(agentRoot,manifest.install.target);
  return {source,target,agentRoot};
}
function syntaxCheck(file){const child=spawnSync(process.execPath,["--experimental-strip-types","--check",file],{encoding:"utf8",timeout:30000}); return {passed:child.status===0,output:[child.stdout,child.stderr].filter(Boolean).join("\n").trim()};}
function atomicWrite(file,content,mode){fs.mkdirSync(path.dirname(file),{recursive:true,mode:0o700}); const temp=path.join(path.dirname(file),`.${path.basename(file)}.${process.pid}.${randomUUID()}.ts`); fs.writeFileSync(temp,content,{encoding:"utf8",mode,flag:"wx"}); const check=syntaxCheck(temp); if(!check.passed){fs.rmSync(temp,{force:true}); throw new Error(`Prepared extension failed syntax check: ${check.output}`);} fs.renameSync(temp,file);}
function status(manifest,env=process.env){const target=resolveTarget(manifest,env); const sourceContent=fs.readFileSync(target.source); const sourceHash=sha256(sourceContent); const exists=fs.existsSync(target.target); const targetHash=exists?sha256(fs.readFileSync(target.target)):null; return {id:"global-recovery-extension",ok:true,sourceHash,targetHash,status:!exists?"missing":targetHash===sourceHash?"already-installed":"outdated",...target};}
function plan(manifest,env=process.env){const current=status(manifest,env); return {ok:true,blocked:false,writes:current.status==="already-installed"?0:1,noop:current.status==="already-installed",targets:[{id:"global-recovery-extension",path:current.target,status:current.status,beforeHash:current.targetHash,afterHash:current.sourceHash,source:current.source}]};}
function apply(manifest,planData,stateDir,env=process.env){const current=status(manifest,env); const expected=planData.targets[0]; if(current.target!==expected.path||current.targetHash!==expected.beforeHash||current.sourceHash!==expected.afterHash)throw new Error("Recovery extension drifted after plan"); const existed=fs.existsSync(current.target); const before=existed?fs.readFileSync(current.target):null; const mode=existed?(fs.statSync(current.target).mode&0o777):0o600; let backupPath=null; if(existed){const root=path.join(stateDir,"backups",manifest.id,planData.planHash); fs.mkdirSync(root,{recursive:true,mode:0o700}); backupPath=path.join(root,"recovery-extension.ts.bak"); fs.writeFileSync(backupPath,before,{mode:0o600,flag:"wx"});} atomicWrite(current.target,fs.readFileSync(current.source,"utf8"),mode); if(sha256(fs.readFileSync(current.target))!==current.sourceHash)throw new Error("Installed extension hash mismatch"); return {targets:[{id:"global-recovery-extension",path:current.target,existed,beforeHash:current.targetHash,afterHash:current.sourceHash,backupPath,mode}]};}
function verify(manifest,env=process.env){const current=status(manifest,env); const syntax=fs.existsSync(current.target)?syntaxCheck(current.target):{passed:false,output:"target missing"}; return {ok:current.status==="already-installed"&&syntax.passed,checks:[{id:"source-hash",passed:current.status==="already-installed",status:current.status},{id:"typescript-syntax",...syntax}],networkUsed:false,billingUsed:false};}
function rollback(receipt){const target=receipt.targets?.[0]; if(!target)throw new Error("Receipt has no recovery target"); if(!fs.existsSync(target.path)||sha256(fs.readFileSync(target.path))!==target.afterHash)throw new Error(`Rollback refused because target drifted: ${target.path}`); if(target.existed){if(!target.backupPath||!fs.existsSync(target.backupPath))throw new Error("Rollback backup missing"); const backup=fs.readFileSync(target.backupPath); if(sha256(backup)!==target.beforeHash)throw new Error("Rollback backup hash mismatch"); atomicWrite(target.path,backup,target.mode||0o600);} else fs.rmSync(target.path,{force:true}); return {writes:1};}
async function main(){const options=parseArgs(process.argv.slice(2)); process.env.PI_PATCH_MANIFEST_PATH=options.manifest; const manifest=readJson(options.manifest); let result; if(options.action==="status")result={ok:true,targets:[status(manifest)]}; else if(options.action==="plan")result=plan(manifest); else if(options.action==="apply"){const receipt=apply(manifest,readJson(options.planFile),options.stateDir); result={ok:true,receipt,result:{writes:1}};} else if(options.action==="verify")result=verify(manifest); else if(options.action==="rollback")result={ok:true,result:rollback(readJson(options.receiptFile))}; else throw new Error(`Unsupported action: ${options.action}`); process.stdout.write(JSON.stringify(result));}
const isMain=process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url); if(isMain)main().catch((error)=>{process.stderr.write(`${error.stack||error.message||error}\n`);process.exit(1);});
export { apply, plan, resolveTarget, rollback, status, verify };
