import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const [html, css, app, readme, technical] = await Promise.all([
  readFile(join(root, "public", "index.html"), "utf8"),
  readFile(join(root, "public", "styles.css"), "utf8"),
  readFile(join(root, "public", "app.js"), "utf8"),
  readFile(join(root, "README.md"), "utf8"),
  readFile(join(root, "TECHNICAL.md"), "utf8"),
]);

assert.match(html, /id="terminalTabsToggleButton"[^>]*aria-controls="terminalTabsDrawerContent"[^>]*aria-expanded="false"/, "terminal summary should control the collapsed drawer");
assert.match(html, /id="terminalTabsDrawerContent"[^>]*aria-label="Terminal navigation"[\s\S]*id="tabBar"[\s\S]*class="terminal-sidebar-actions"[^>]*aria-label="Tab and workspace actions"[\s\S]*id="closeAllTabsButton"/, "drawer should reuse canonical tabs and workspace actions");
assert.match(html, /id="terminalTabsBackdrop"[^>]*aria-label="Close terminal navigation"[^>]*hidden/, "drawer should expose an accessible backdrop close target");
assert.match(css, /body\.mobile-tabs-expanded \.terminal-tabs-shell \{[\s\S]*?position:\s*fixed;[\s\S]*?top:\s*0;[\s\S]*?right:\s*0;[\s\S]*?left:\s*0;[\s\S]*?width:\s*100vw;[\s\S]*?height:\s*var\(--visual-viewport-height, 100dvh\);[\s\S]*?border-radius:\s*0;/, "expanded terminal navigation should fill the visual viewport");
assert.match(css, /body\.mobile-tabs-expanded \.terminal-tabs \{[\s\S]*?position:\s*static;[\s\S]*?flex-direction:\s*column;[\s\S]*?overflow-y:\s*auto/, "drawer tabs should follow the vertical left-sidebar model");
assert.match(app, /function setMobileTabsExpanded\(expanded, \{ restoreFocus = false \} = \{\}\)[\s\S]*?setComposerActionsOpen\(false\)[\s\S]*?terminalTabsBackdrop\.hidden = !mobileTabsExpanded[\s\S]*?focusReturn\.focus/, "drawer state should coordinate competing surfaces and restore focus");
assert.match(app, /node\.addEventListener\("pointerenter", \(event\) => \{\n\s+if \(event\.pointerType === "touch"\) return;\n\s+scheduleFooterTooltip\(node\);/, "touch pointers should not schedule floating hover tooltips");
assert.match(app, /node\.addEventListener\("focus", \(\) => \{\n\s+if \(!node\.matches\(":focus-visible"\)\) return;\n\s+showFooterTooltip\(node\);/, "touch focus should not open a floating tooltip while keyboard focus remains supported");
assert.match(css, /@media \(hover: none\) and \(pointer: coarse\) \{[\s\S]*?\[data-tooltip\]:not\(:focus-visible\):not\(\.tooltip-open\)::before,[\s\S]*?::after \{[\s\S]*?display:\s*none !important;[\s\S]*?opacity:\s*0 !important;/, "coarse touch layouts should suppress hover-only pseudo tooltips");
assert.match(app, /function setMobileFooterExpanded\(expanded, \{ restoreFocus = false \} = \{\}\)[\s\S]*?button\.textContent = mobileFooterExpanded \? "−" : "Details"[\s\S]*?"Minimize Git footer details"[\s\S]*?activateDrawerModal\(elements\.statusBar, button[\s\S]*?setMobileFooterExpanded\(false, \{ restoreFocus: true \}\)/, "expanded mobile footer details should use a modal top minimize control with focus restoration");
assert.match(app, /const footerToggle = make\("button", "footer-details-toggle", mobileFooterExpanded \? "−" : "Details"\)[\s\S]*?aria-label[\s\S]*?setMobileFooterExpanded\(!mobileFooterExpanded, \{ restoreFocus: true \}\)/, "rendered footer details should expose only the minimize symbol while expanded");
assert.match(css, /html:not\(\[data-mobile-shell="v2"\]\):not\(\[data-tablet-shell="v2"\]\) body\.footer-details-expanded \.statusbar-git-footer \{[\s\S]*?position:\s*fixed;[\s\S]*?inset:\s*0;[\s\S]*?width:\s*100vw;[\s\S]*?height:\s*var\(--visual-viewport-height, 100dvh\);[\s\S]*?border-radius:\s*0;/, "legacy-mobile Git footer details should fill the complete visual viewport without owning v2 surfaces");
assert.match(css, /body\.footer-details-expanded \.statusbar-git-footer \{[\s\S]*?align-content:\s*start;[\s\S]*?grid-auto-rows:\s*max-content;[\s\S]*?body\.footer-details-expanded \.footer-line-main,[\s\S]*?body\.footer-details-expanded \.footer-line-meta \{[\s\S]*?grid-template-columns:\s*repeat\(2, minmax\(0, 1fr\)\);[\s\S]*?\.footer-line-main::before \{ content:\s*"Session"; \}[\s\S]*?\.footer-line-meta::before \{ content:\s*"Workspace, Git & runtime"; \}/, "expanded mobile Git details should pack compact two-column sections at the top of the overlay");
assert.match(css, /body\.footer-details-expanded \.footer-line-main > \.footer-metric:nth-child\(odd\):last-child \{ grid-column:\s*1 \/ -1; \}[\s\S]*?body\.footer-details-expanded \.footer-workspace,[\s\S]*?body\.footer-details-expanded \.footer-context,[\s\S]*?body\.footer-details-expanded \.footer-model,[\s\S]*?grid-column:\s*1 \/ -1;/, "odd metrics and long footer metadata should span the mobile details grid without leaving holes");
assert.match(css, /html:not\(\[data-mobile-shell="v2"\]\):not\(\[data-tablet-shell="v2"\]\) \.statusbar-git-footer \.git-footer-refresh-button \{ display:\s*none; \}[\s\S]*?body\.footer-details-expanded \.statusbar-git-footer \.git-footer-refresh-button \{[\s\S]*?display:\s*inline-grid;[\s\S]*?min-width:\s*44px;[\s\S]*?min-height:\s*44px;/, "legacy-mobile Git footer refresh should be available only in the expanded details overlay");
assert.match(css, /body\.footer-details-expanded \.side-panel-toggle-button,[\s\S]*?body\.footer-details-expanded \.side-panel-expand-button,[\s\S]*?body\.composer-actions-open \.side-panel-toggle-button,[\s\S]*?body\.composer-actions-open \.side-panel-expand-button,[\s\S]*?body\.mobile-tabs-expanded \.side-panel-toggle-button,[\s\S]*?body\.mobile-tabs-expanded \.side-panel-expand-button \{\n\s+display:\s*none !important;/, "full-screen mobile Git, More, and terminal overlays should hide both side-panel disclosure controls");
assert.match(css, /body\.mobile-tabs-expanded \.terminal-tabs-shell\[aria-modal="true"\] \{\n\s+z-index:\s*122;/, "the modal terminal drawer should retain its layer above the blurred backdrop while child menus are open");
assert.match(css, /\.terminal-tab-meta \{ display:\s*none; \}\n\s+\.terminal-tab-group > \.terminal-tab-group-button > \.terminal-tab-meta \{ display:\s*block; \}/, "mobile group buttons should retain the desktop cwd metadata while standalone tab metadata stays compact");
assert.match(css, /\.terminal-tabs:has\(> \.terminal-tab-group\.menu-open:not\(\.terminal-tab-subagent-group\)\) > \.terminal-new-tab-menu \{\n\s+display:\s*none;/, "mobile tabs should hide the overall new-tab menu only while a regular group exposes its scoped add action");
assert.match(css, /\.footer-details-toggle \{\n\s+display:\s*block;\n\s+min-width:\s*44px;\n\s+min-height:\s*44px;/, "collapsed Details should retain a 44px mobile touch target");
assert.match(app, /function runFooterControlAction\(action, event\) \{\n\s+if \(mobileFooterExpanded\) setMobileFooterExpanded\(false, \{ restoreFocus: false \}\);\n\s+return action\(event\);/, "footer actions should deactivate the full-screen footer before opening dialogs or other surfaces");

assert.match(html, /id="composerActionsButton"[^>]*aria-controls="composerActionsPanel"[^>]*aria-expanded="false"[^>]*>More<\/button>/, "composer should expose one labelled secondary-action trigger");
assert.match(html, /id="composerActionsPanel"[^>]*aria-label="More composer actions"[\s\S]*Session &amp; workspace[\s\S]*Tools &amp; commands[\s\S]*Context &amp; modes/, "secondary actions should be grouped in task order");
assert.match(app, /function syncMobileComposerDisclosureLayout\(\)[\s\S]*?isMobileView\(\) && !isMobileShellV2Active\(\)[\s\S]*?composerActionsPanel\.append\(node\)/, "legacy mobile should reuse canonical secondary controls in the panel");
assert.match(css, /body\.mobile-composer-disclosure \.composer-input-row \{[\s\S]*?grid-template-columns:\s*minmax\(0, 1fr\) 44px/, "collapsed composer should keep the prompt and attachment control in the input row");
assert.match(css, /\.chat > \.run-indicator-message \{\n\s+position:\s*sticky;[\s\S]*?bottom:\s*calc\(0\.12rem \+ var\(--keyboard-inset-bottom, 0px\)\);[\s\S]*?\.chat > \.run-indicator-message \.run-indicator-row \{[\s\S]*?grid-template-columns:\s*auto auto minmax\(0, 1fr\);[\s\S]*?\.run-indicator-meta \{[\s\S]*?text-overflow:\s*ellipsis;[\s\S]*?white-space:\s*nowrap;/, "mobile streamed output should keep a one-line run indicator pinned at the transcript edge");
assert.match(css, /\.todo-widget:not\(\[open\]\) \.todo-widget-summary \{ display:\s*block; \}[\s\S]*?\.todo-widget:not\(\[open\]\) \.todo-widget-goal,[\s\S]*?\.todo-widget:not\(\[open\]\) \.todo-widget-progress \{ display:\s*none; \}[\s\S]*?\.todo-widget:not\(\[open\]\) \.todo-widget-title \{[\s\S]*?text-overflow:\s*ellipsis;[\s\S]*?white-space:\s*nowrap;/, "collapsed mobile todo progress should stay on one overflow-safe summary line until expanded");
assert.match(css, /\/\* Balanced phone density:[\s\S]*?--mobile-control-size:\s*40px;[\s\S]*?--mobile-page-gutter:\s*0\.5rem;[\s\S]*?--mobile-body-text:\s*0\.86rem;/, "balanced phone density should use one coherent compact scale");
assert.match(css, /body\.mobile-composer-disclosure \.composer-input-row \{ grid-template-columns:\s*minmax\(0, 1fr\) var\(--mobile-control-size\);[\s\S]*?body\.mobile-composer-disclosure \.composer-actions-panel \{[\s\S]*?padding:\s*calc\(3\.5rem \+ env\(safe-area-inset-top\)\)/, "legacy composer and full-screen More surfaces should use the compact scale");
assert.match(css, /html\[data-mobile-shell="v2"\] \.mobile-shell-appbar \{[\s\S]*?min-height:\s*calc\(68px \+ env\(safe-area-inset-top\)\);[\s\S]*?\.mobile-shell-nav \{[\s\S]*?min-height:\s*calc\(54px \+ env\(safe-area-inset-bottom\)\);/, "Mobile Experience v2 chrome should use the compact app bar and navigation heights");
assert.match(css, /html\[data-mobile-shell="v2"\] \.mobile-shell-session-button \{ grid-column:\s*1; grid-row:\s*1;[\s\S]*?#mobileSearchButton \{ grid-column:\s*2; grid-row:\s*1; \}[\s\S]*?#mobileMoreButton \{ grid-column:\s*3; grid-row:\s*1; \}[\s\S]*?\.mobile-shell-indicators \{ grid-row:\s*2;/, "v2 app-bar controls should share the first row instead of creating a sparse third row");
assert.match(css, /body\.mobile-composer-disclosure\.pi-run-active:not\(\.mobile-keyboard-open\) \.composer-row > #abortButton \{ order:\s*1; \}[\s\S]*?#steerButton \{ order:\s*2; \}[\s\S]*?#followUpButton \{ order:\s*3; \}[\s\S]*?\.composer-actions-button \{ order:\s*4; \}[\s\S]*?#sendButton \{ order:\s*5; \}/, "active primary controls should remain on one predictable row");
assert.match(css, /body\.mobile-composer-disclosure \.composer-actions-panel \{[\s\S]*?position:\s*fixed;[\s\S]*?inset:\s*0;[\s\S]*?width:\s*100vw;[\s\S]*?height:\s*var\(--visual-viewport-height, 100dvh\);[\s\S]*?max-height:\s*none;[\s\S]*?border-radius:\s*0;/, "secondary actions should use the complete visual viewport");
assert.match(app, /composerActionsButton\.textContent = shouldOpen \? "−" : "More";[\s\S]*?aria-label", shouldOpen \? "Minimize more composer actions" : "Show more composer actions"/, "the open More overlay should expose an accessible minimize symbol instead of a Less label");
assert.match(css, /body\.mobile-composer-disclosure\.composer-actions-open \.composer-actions-panel \{ display:\s*grid; \}[\s\S]*?body\.mobile-composer-disclosure\.composer-actions-open \.composer-actions-button \{[\s\S]*?position:\s*fixed;[\s\S]*?top:\s*max\(0\.65rem, env\(safe-area-inset-top\)\);[\s\S]*?right:\s*max\(0\.7rem, env\(safe-area-inset-right\)\);[\s\S]*?width:\s*44px;[\s\S]*?height:\s*44px;/, "secondary actions should appear only after disclosure and keep a 44px minimize control reachable at the top-right");
assert.match(html, /id="sidePanelEditButton"[^>]*aria-pressed="false"[^>]*aria-label="Edit Control Deck section order"/, "mobile Control Deck should expose a default-off Edit mode");
assert.match(app, /function moveSidePanelSectionByOffset\(sectionId, offset\) \{\n\s+if \(!sidePanelSectionEditMode\) return false;[\s\S]*?function beginSidePanelSectionPointerDrag\(event, sectionId\) \{\n\s+if \(!sidePanelSectionEditMode \|\|/, "mobile Control Deck reordering should fail closed until Edit is active");
assert.match(css, /\.side-panel-section-toggle\[data-side-panel-section-toggle\] \{\n\s+cursor:\s*pointer;\n\s+touch-action:\s*manipulation;[\s\S]*?\.side-panel\.section-edit-mode \.side-panel-section-toggle\[data-side-panel-section-toggle\] \{[\s\S]*?cursor:\s*grab;[\s\S]*?touch-action:\s*none;/, "mobile section headers should switch from native tap behavior to drag capture in Edit mode");
assert.match(css, /body\.mobile-composer-disclosure\.mobile-keyboard-open \.composer-row \{[\s\S]*?repeat\(4,[\s\S]*?body\.mobile-composer-disclosure\.mobile-keyboard-open \.composer-actions-button,[\s\S]*?display:\s*none !important/, "keyboard-open mode should retain primary controls and suppress secondary chrome");

assert.match(readme, /On a phone, tap the current terminal name to open full-screen terminal navigation[\s\S]*Grouped terminals use their title as a dropdown[\s\S]*tap \*\*More\*\* to open[\s\S]*in a full-screen overlay[\s\S]*Git footer \*\*Details\*\* opens full-screen with refresh inside and a top `−` button[\s\S]*Hover-only tooltips stay hidden on touch controls[\s\S]*\*\*Control Deck\*\*[\s\S]*tap \*\*Edit\*\*[\s\S]*tap \*\*Done\*\*/, "README should explain the full-screen mobile paths and explicit Control Deck editing");
assert.match(technical, /## Mobile layout[\s\S]*open full-screen terminal navigation[\s\S]*regular or subagent terminal-group title is a dropdown button[\s\S]*Git footer \*\*Details\*\* opens as a full-screen legacy-mobile overlay[\s\S]*Tap \*\*More\*\* to open[\s\S]*accessible top-right `−` control[\s\S]*Control Deck section order is locked by default on desktop and mobile[\s\S]*Select \*\*Edit\*\*[\s\S]*`Alt\+ArrowUp` \/ `Alt\+ArrowDown`[\s\S]*select \*\*Done\*\*[\s\S]*Touch pointers do not schedule hover-only tooltips[\s\S]*Tablet layout, desktop tab placement/, "technical reference should document transient Control Deck Edit mode and mobile controls");

console.log("mobile compact layout contracts passed");
